name             'oracle_instant_client'
maintainer       'Biola University'
maintainer_email 'adam.crownoble@biola.edu'
description      'Installs Oracle Instant Client'
source_url       'https://github.com/biola/chef-oracle_instant_client'
issues_url       'https://github.com/biola/chef-oracle_instant_client/issues'
version          '0.2.1'
recipe           'oracle_instant_client', 'Installs Oracle Instant Client libraries'
supports         'ubuntu'
